// #4338ca indigo-700, #8b5cf6 violet-500, #312e81 indigo-900
// #22d3ee cyan-400, #7dd3fc sky-300

import type { Metadata } from "next";
import { Agbalumo } from "next/font/google";
import "./globals.css";

const font = Agbalumo({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  );
}
